export const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMPANY_MASTER: 'COMPANY_MASTER',
  RAILWAY_MASTER: 'RAILWAY_MASTER',
  ADMIN: 'ADMIN',
  RAILWAY_ADMIN: 'RAILWAY_ADMIN',
  RAILWAY_SUPERVISOR: 'RAILWAY_SUPERVISOR',
  CONTRACTOR_SUPERVISOR: 'CONTRACTOR_SUPERVISOR',
  CTS: 'CTS',
  WORKER: 'WORKER',
  RAILWAY_WORKER: 'RAILWAY_WORKER',
  JANITOR: 'JANITOR',
  ATTENDANT: 'ATTENDANT'
});

export const ROLE_HIERARCHY = Object.freeze({
  SUPER_ADMIN: 100,
  COMPANY_MASTER: 90,
  RAILWAY_MASTER: 80,
  ADMIN: 70,
  RAILWAY_ADMIN: 60,
  RAILWAY_SUPERVISOR: 50,
  CONTRACTOR_SUPERVISOR: 40,
  CTS: 30,
  WORKER: 10,
  RAILWAY_WORKER: 10,
  JANITOR: 10,
  ATTENDANT: 10
});

export const PERMISSIONS = Object.freeze({
  // User management
  CREATE_USER: 'create_user',
  UPDATE_USER: 'update_user',
  APPROVE_USER: 'approve_user',
  REJECT_USER: 'reject_user',
  SUSPEND_USER: 'suspend_user',
  VIEW_USERS: 'view_users',
  VIEW_USER_DETAILS: 'view_user_details',

  // Entity management
  CREATE_ENTITY: 'create_entity',
  UPDATE_ENTITY: 'update_entity',
  APPROVE_ENTITY: 'approve_entity',
  REJECT_ENTITY: 'reject_entity',
  SUSPEND_ENTITY: 'suspend_entity',
  VIEW_ENTITIES: 'view_entities',

  // Contract management
  CREATE_CONTRACT: 'create_contract',
  UPDATE_CONTRACT: 'update_contract',
  VIEW_CONTRACTS: 'view_contracts',

  // Train management
  CREATE_TRAIN: 'create_train',
  UPDATE_TRAIN: 'update_train',
  VIEW_TRAINS: 'view_trains',

  // Run instances
  CREATE_RUN_INSTANCE: 'create_run_instance',
  UPDATE_RUN_INSTANCE: 'update_run_instance',
  ACTIVATE_JOURNEY: 'activate_journey',
  COMPLETE_JOURNEY: 'complete_journey',
  VIEW_RUN_INSTANCES: 'view_run_instances',

  // Forms
  SUBMIT_COACH_FORM: 'submit_coach_form',
  APPROVE_FORM_MANPOWER: 'approve_form_manpower',
  SCORE_FORM: 'score_form',
  ACCEPT_RATING: 'accept_rating',
  REJECT_FORM: 'reject_form',
  VIEW_FORMS: 'view_forms',

  // Emergency
  CREATE_EMERGENCY_TASK: 'create_emergency_task',

  // Reports
  VIEW_REPORTS: 'view_reports',
  GENERATE_REPORTS: 'generate_reports',

  // Admin
  VIEW_ANALYTICS: 'view_analytics',
  MANAGE_SYSTEM: 'manage_system'
});

export const ROLE_PERMISSIONS = Object.freeze({
  SUPER_ADMIN: Object.values(PERMISSIONS),

  COMPANY_MASTER: [
    PERMISSIONS.CREATE_USER, PERMISSIONS.UPDATE_USER, PERMISSIONS.APPROVE_USER,
    PERMISSIONS.REJECT_USER, PERMISSIONS.SUSPEND_USER, PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_USER_DETAILS, PERMISSIONS.CREATE_ENTITY, PERMISSIONS.UPDATE_ENTITY,
    PERMISSIONS.APPROVE_ENTITY, PERMISSIONS.REJECT_ENTITY, PERMISSIONS.SUSPEND_ENTITY,
    PERMISSIONS.VIEW_ENTITIES, PERMISSIONS.CREATE_CONTRACT, PERMISSIONS.UPDATE_CONTRACT,
    PERMISSIONS.VIEW_CONTRACTS, PERMISSIONS.CREATE_TRAIN, PERMISSIONS.UPDATE_TRAIN,
    PERMISSIONS.VIEW_TRAINS, PERMISSIONS.CREATE_RUN_INSTANCE, PERMISSIONS.UPDATE_RUN_INSTANCE,
    PERMISSIONS.ACTIVATE_JOURNEY, PERMISSIONS.COMPLETE_JOURNEY, PERMISSIONS.VIEW_RUN_INSTANCES,
    PERMISSIONS.VIEW_FORMS, PERMISSIONS.VIEW_REPORTS, PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS, PERMISSIONS.MANAGE_SYSTEM
  ],

  RAILWAY_MASTER: [
    PERMISSIONS.CREATE_USER, PERMISSIONS.UPDATE_USER, PERMISSIONS.APPROVE_USER,
    PERMISSIONS.REJECT_USER, PERMISSIONS.SUSPEND_USER, PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_USER_DETAILS, PERMISSIONS.VIEW_ENTITIES, PERMISSIONS.VIEW_CONTRACTS,
    PERMISSIONS.CREATE_TRAIN, PERMISSIONS.UPDATE_TRAIN, PERMISSIONS.VIEW_TRAINS,
    PERMISSIONS.CREATE_RUN_INSTANCE, PERMISSIONS.UPDATE_RUN_INSTANCE,
    PERMISSIONS.ACTIVATE_JOURNEY, PERMISSIONS.COMPLETE_JOURNEY, PERMISSIONS.VIEW_RUN_INSTANCES,
    PERMISSIONS.VIEW_FORMS, PERMISSIONS.VIEW_REPORTS, PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS
  ],

  ADMIN: [
    PERMISSIONS.CREATE_USER, PERMISSIONS.UPDATE_USER, PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_USER_DETAILS, PERMISSIONS.VIEW_ENTITIES, PERMISSIONS.VIEW_CONTRACTS,
    PERMISSIONS.VIEW_TRAINS, PERMISSIONS.VIEW_RUN_INSTANCES, PERMISSIONS.VIEW_FORMS,
    PERMISSIONS.VIEW_REPORTS, PERMISSIONS.UPDATE_RUN_INSTANCE
  ],

  RAILWAY_ADMIN: [
    PERMISSIONS.VIEW_USERS, PERMISSIONS.VIEW_USER_DETAILS, PERMISSIONS.VIEW_ENTITIES,
    PERMISSIONS.VIEW_CONTRACTS, PERMISSIONS.VIEW_TRAINS, PERMISSIONS.VIEW_RUN_INSTANCES,
    PERMISSIONS.VIEW_FORMS, PERMISSIONS.VIEW_REPORTS, PERMISSIONS.SUBMIT_COACH_FORM,
    PERMISSIONS.APPROVE_FORM_MANPOWER, PERMISSIONS.SCORE_FORM, PERMISSIONS.REJECT_FORM
  ],

  RAILWAY_SUPERVISOR: [
    PERMISSIONS.VIEW_USERS, PERMISSIONS.VIEW_USER_DETAILS, PERMISSIONS.VIEW_TRAINS,
    PERMISSIONS.VIEW_RUN_INSTANCES, PERMISSIONS.VIEW_FORMS, PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.APPROVE_FORM_MANPOWER, PERMISSIONS.SCORE_FORM, PERMISSIONS.REJECT_FORM
  ],

  CONTRACTOR_SUPERVISOR: [
    PERMISSIONS.VIEW_USERS, PERMISSIONS.VIEW_USER_DETAILS, PERMISSIONS.VIEW_TRAINS,
    PERMISSIONS.VIEW_RUN_INSTANCES, PERMISSIONS.VIEW_FORMS, PERMISSIONS.SUBMIT_COACH_FORM,
    PERMISSIONS.ACCEPT_RATING
  ],

  CTS: [
    PERMISSIONS.VIEW_TRAINS, PERMISSIONS.VIEW_RUN_INSTANCES, PERMISSIONS.CREATE_EMERGENCY_TASK
  ],

  WORKER: [
    PERMISSIONS.VIEW_RUN_INSTANCES
  ],

  RAILWAY_WORKER: [
    PERMISSIONS.VIEW_RUN_INSTANCES
  ],

  JANITOR: [
    PERMISSIONS.VIEW_RUN_INSTANCES
  ],

  ATTENDANT: [
    PERMISSIONS.VIEW_RUN_INSTANCES
  ]
});
