export const ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMPANY_MASTER: 'COMPANY_MASTER',
  RAILWAY_MASTER: 'RAILWAY_MASTER',
  ADMIN: 'ADMIN',
  RAILWAY_ADMIN: 'RAILWAY_ADMIN',
  RAILWAY_SUPERVISOR: 'RAILWAY_SUPERVISOR',
  CONTRACTOR_SUPERVISOR: 'CONTRACTOR_SUPERVISOR',
  CTS: 'CTS',
  WORKER: 'WORKER',
  RAILWAY_WORKER: 'RAILWAY_WORKER',
  JANITOR: 'JANITOR',
  ATTENDANT: 'ATTENDANT'
});

export const ROLE_HIERARCHY = Object.freeze({
  SUPER_ADMIN: 100,
  COMPANY_MASTER: 90,
  RAILWAY_MASTER: 80,
  ADMIN: 70,
  RAILWAY_ADMIN: 60,
  RAILWAY_SUPERVISOR: 50,
  CONTRACTOR_SUPERVISOR: 40,
  CTS: 30,
  WORKER: 10,
  RAILWAY_WORKER: 10,
  JANITOR: 10,
  ATTENDANT: 10
});

export const PERMISSIONS = Object.freeze({
  // User management
  CREATE_USER: 'create_user',
  UPDATE_USER: 'update_user',
  APPROVE_USER: 'approve_user',
  REJECT_USER: 'reject_user',
  SUSPEND_USER: 'suspend_user',
  VIEW_USERS: 'view_users',
  VIEW_USER_DETAILS: 'view_user_details',

  // Entity management
  CREATE_ENTITY: 'create_entity',
  UPDATE_ENTITY: 'update_entity',
  APPROVE_ENTITY: 'approve_entity',
  REJECT_ENTITY: 'reject_entity',
  SUSPEND_ENTITY: 'suspend_entity',
  VIEW_ENTITIES: 'view_entities',

  // Contract management
  CREATE_CONTRACT: 'create_contract',
  UPDATE_CONTRACT: 'update_contract',
  VIEW_CONTRACTS: 'view_contracts',

  // Train management
  CREATE_TRAIN: 'create_train',
  UPDATE_TRAIN: 'update_train',
  VIEW_TRAINS: 'view_trains',

  // Run instances
  CREATE_RUN_INSTANCE: 'create_run_instance',
  UPDATE_RUN_INSTANCE: 'update_run_instance',
  ACTIVATE_JOURNEY: 'activate_journey',
  COMPLETE_JOURNEY: 'complete_journey',
  VIEW_RUN_INSTANCES: 'view_run_instances',

  // Forms
  SUBMIT_COACH_FORM: 'submit_coach_form',
  APPROVE_FORM_MANPOWER: 'approve_form_manpower',
  SCORE_FORM: 'score_form',
  ACCEPT_RATING: 'accept_rating',
  REJECT_FORM: 'reject_form',
  VIEW_FORMS: 'view_forms',

  // Emergency
  CREATE_EMERGENCY_TASK: 'create_emergency_task',

  // Reports
  VIEW_REPORTS: 'view_reports',
  GENERATE_REPORTS: 'generate_reports',

  // Platform Master
  MANAGE_PLATFORMS: 'manage_platforms',
  VIEW_PLATFORMS: 'view_platforms',

  // Area Master
  MANAGE_AREAS: 'manage_areas',
  VIEW_AREAS: 'view_areas',

  // Frequency Configuration
  MANAGE_FREQUENCIES: 'manage_frequencies',
  VIEW_FREQUENCIES: 'view_frequencies',
  GENERATE_TASKS: 'generate_tasks',

  // Shift Management
  MANAGE_SHIFTS: 'manage_shifts',
  VIEW_SHIFTS: 'view_shifts',
  ASSIGN_SHIFT: 'assign_shift',

  // Deployment
  MANAGE_DEPLOYMENTS: 'manage_deployments',
  VIEW_DEPLOYMENTS: 'view_deployments',

  // Geofence
  MANAGE_GEOFENCES: 'manage_geofences',
  VIEW_GEOFENCES: 'view_geofences',

  // Inspection
  MANAGE_INSPECTIONS: 'manage_inspections',
  VIEW_INSPECTIONS: 'view_inspections',
  APPROVE_INSPECTION: 'approve_inspection',
  SCORE_INSPECTION: 'score_inspection',

  // Petty Issue
  MANAGE_PETTY_ISSUES: 'manage_petty_issues',
  VIEW_PETTY_ISSUES: 'view_petty_issues',
  RESOLVE_PETTY_ISSUE: 'resolve_petty_issue',

  // Activity
  MANAGE_ACTIVITIES: 'manage_activities',
  VIEW_ACTIVITIES: 'view_activities',

  // Machine
  MANAGE_MACHINES: 'manage_machines',
  VIEW_MACHINES: 'view_machines',

  // Material
  MANAGE_MATERIALS: 'manage_materials',
  VIEW_MATERIALS: 'view_materials',

  // Pest Control
  MANAGE_PEST_CONTROL: 'manage_pest_control',
  VIEW_PEST_CONTROL: 'view_pest_control',

  // Garbage
  MANAGE_GARBAGE: 'manage_garbage',
  VIEW_GARBAGE: 'view_garbage',

  // Complaint
  CREATE_COMPLAINT: 'create_complaint',
  VIEW_COMPLAINTS: 'view_complaints',
  MANAGE_COMPLAINTS: 'manage_complaints',

  // Scorecard
  MANAGE_SCORECARDS: 'manage_scorecards',
  VIEW_SCORECARDS: 'view_scorecards',

  // Execution
  MANAGE_EXECUTION: 'manage_execution',
  VIEW_EXECUTION: 'view_execution',
  APPROVE_EXECUTION: 'approve_execution',

  // Search
  VIEW_SEARCH: 'view_search',

  // Admin
  VIEW_ANALYTICS: 'view_analytics',
  MANAGE_SYSTEM: 'manage_system',
  VIEW_SYSTEM: 'view_system'
});

export const ROLE_PERMISSIONS = Object.freeze({
  SUPER_ADMIN: Object.values(PERMISSIONS),

  COMPANY_MASTER: [
    PERMISSIONS.CREATE_USER, PERMISSIONS.UPDATE_USER, PERMISSIONS.APPROVE_USER,
    PERMISSIONS.REJECT_USER, PERMISSIONS.SUSPEND_USER, PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_USER_DETAILS, PERMISSIONS.CREATE_ENTITY, PERMISSIONS.UPDATE_ENTITY,
    PERMISSIONS.APPROVE_ENTITY, PERMISSIONS.REJECT_ENTITY, PERMISSIONS.SUSPEND_ENTITY,
    PERMISSIONS.VIEW_ENTITIES, PERMISSIONS.CREATE_CONTRACT, PERMISSIONS.UPDATE_CONTRACT,
    PERMISSIONS.VIEW_CONTRACTS, PERMISSIONS.CREATE_TRAIN, PERMISSIONS.UPDATE_TRAIN,
    PERMISSIONS.VIEW_TRAINS, PERMISSIONS.CREATE_RUN_INSTANCE, PERMISSIONS.UPDATE_RUN_INSTANCE,
    PERMISSIONS.ACTIVATE_JOURNEY, PERMISSIONS.COMPLETE_JOURNEY, PERMISSIONS.VIEW_RUN_INSTANCES,
    PERMISSIONS.VIEW_FORMS, PERMISSIONS.VIEW_REPORTS, PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS, PERMISSIONS.MANAGE_SYSTEM, PERMISSIONS.VIEW_SYSTEM,
    PERMISSIONS.MANAGE_PLATFORMS, PERMISSIONS.VIEW_PLATFORMS,
    PERMISSIONS.MANAGE_AREAS, PERMISSIONS.VIEW_AREAS,
    PERMISSIONS.MANAGE_FREQUENCIES, PERMISSIONS.VIEW_FREQUENCIES, PERMISSIONS.GENERATE_TASKS,
    PERMISSIONS.MANAGE_SHIFTS, PERMISSIONS.VIEW_SHIFTS, PERMISSIONS.ASSIGN_SHIFT,
    PERMISSIONS.MANAGE_DEPLOYMENTS, PERMISSIONS.VIEW_DEPLOYMENTS,
    PERMISSIONS.MANAGE_GEOFENCES, PERMISSIONS.VIEW_GEOFENCES,
    PERMISSIONS.MANAGE_INSPECTIONS, PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.APPROVE_INSPECTION, PERMISSIONS.SCORE_INSPECTION,
    PERMISSIONS.MANAGE_PETTY_ISSUES, PERMISSIONS.VIEW_PETTY_ISSUES, PERMISSIONS.RESOLVE_PETTY_ISSUE,
    PERMISSIONS.VIEW_SEARCH,
    PERMISSIONS.MANAGE_ACTIVITIES, PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.MANAGE_MACHINES, PERMISSIONS.VIEW_MACHINES,
    PERMISSIONS.MANAGE_MATERIALS, PERMISSIONS.VIEW_MATERIALS,
    PERMISSIONS.MANAGE_PEST_CONTROL, PERMISSIONS.VIEW_PEST_CONTROL,
    PERMISSIONS.MANAGE_GARBAGE, PERMISSIONS.VIEW_GARBAGE,
    PERMISSIONS.CREATE_COMPLAINT, PERMISSIONS.VIEW_COMPLAINTS, PERMISSIONS.MANAGE_COMPLAINTS,
    PERMISSIONS.MANAGE_SCORECARDS, PERMISSIONS.VIEW_SCORECARDS,
    PERMISSIONS.MANAGE_EXECUTION, PERMISSIONS.VIEW_EXECUTION, PERMISSIONS.APPROVE_EXECUTION
  ],

  RAILWAY_MASTER: [
    PERMISSIONS.CREATE_USER, PERMISSIONS.UPDATE_USER, PERMISSIONS.APPROVE_USER,
    PERMISSIONS.REJECT_USER, PERMISSIONS.SUSPEND_USER, PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_USER_DETAILS, PERMISSIONS.VIEW_ENTITIES, PERMISSIONS.VIEW_CONTRACTS,
    PERMISSIONS.CREATE_TRAIN, PERMISSIONS.UPDATE_TRAIN, PERMISSIONS.VIEW_TRAINS,
    PERMISSIONS.CREATE_RUN_INSTANCE, PERMISSIONS.UPDATE_RUN_INSTANCE,
    PERMISSIONS.ACTIVATE_JOURNEY, PERMISSIONS.COMPLETE_JOURNEY, PERMISSIONS.VIEW_RUN_INSTANCES,
    PERMISSIONS.VIEW_FORMS, PERMISSIONS.VIEW_REPORTS, PERMISSIONS.GENERATE_REPORTS,
    PERMISSIONS.VIEW_ANALYTICS, PERMISSIONS.MANAGE_SYSTEM, PERMISSIONS.VIEW_SYSTEM,
    PERMISSIONS.MANAGE_PLATFORMS, PERMISSIONS.VIEW_PLATFORMS,
    PERMISSIONS.MANAGE_AREAS, PERMISSIONS.VIEW_AREAS,
    PERMISSIONS.MANAGE_FREQUENCIES, PERMISSIONS.VIEW_FREQUENCIES, PERMISSIONS.GENERATE_TASKS,
    PERMISSIONS.MANAGE_SHIFTS, PERMISSIONS.VIEW_SHIFTS, PERMISSIONS.ASSIGN_SHIFT,
    PERMISSIONS.MANAGE_DEPLOYMENTS, PERMISSIONS.VIEW_DEPLOYMENTS,
    PERMISSIONS.MANAGE_GEOFENCES, PERMISSIONS.VIEW_GEOFENCES,
    PERMISSIONS.MANAGE_INSPECTIONS, PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.APPROVE_INSPECTION, PERMISSIONS.SCORE_INSPECTION,
    PERMISSIONS.MANAGE_PETTY_ISSUES, PERMISSIONS.VIEW_PETTY_ISSUES, PERMISSIONS.RESOLVE_PETTY_ISSUE,
    PERMISSIONS.VIEW_SEARCH,
    PERMISSIONS.MANAGE_ACTIVITIES, PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.MANAGE_MACHINES, PERMISSIONS.VIEW_MACHINES,
    PERMISSIONS.MANAGE_MATERIALS, PERMISSIONS.VIEW_MATERIALS,
    PERMISSIONS.MANAGE_PEST_CONTROL, PERMISSIONS.VIEW_PEST_CONTROL,
    PERMISSIONS.MANAGE_GARBAGE, PERMISSIONS.VIEW_GARBAGE,
    PERMISSIONS.CREATE_COMPLAINT, PERMISSIONS.VIEW_COMPLAINTS, PERMISSIONS.MANAGE_COMPLAINTS,
    PERMISSIONS.MANAGE_SCORECARDS, PERMISSIONS.VIEW_SCORECARDS,
    PERMISSIONS.MANAGE_EXECUTION, PERMISSIONS.VIEW_EXECUTION, PERMISSIONS.APPROVE_EXECUTION
  ],

  ADMIN: [
    PERMISSIONS.CREATE_USER, PERMISSIONS.UPDATE_USER, PERMISSIONS.VIEW_USERS,
    PERMISSIONS.VIEW_USER_DETAILS, PERMISSIONS.VIEW_ENTITIES, PERMISSIONS.VIEW_CONTRACTS,
    PERMISSIONS.VIEW_TRAINS, PERMISSIONS.VIEW_RUN_INSTANCES, PERMISSIONS.VIEW_FORMS,
    PERMISSIONS.VIEW_REPORTS, PERMISSIONS.UPDATE_RUN_INSTANCE,
    PERMISSIONS.VIEW_PLATFORMS, PERMISSIONS.VIEW_AREAS,
    PERMISSIONS.VIEW_FREQUENCIES,
    PERMISSIONS.VIEW_SHIFTS, PERMISSIONS.ASSIGN_SHIFT,
    PERMISSIONS.VIEW_DEPLOYMENTS,
    PERMISSIONS.VIEW_GEOFENCES,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.VIEW_PETTY_ISSUES,
    PERMISSIONS.VIEW_SEARCH,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.VIEW_MACHINES,
    PERMISSIONS.VIEW_MATERIALS,
    PERMISSIONS.VIEW_PEST_CONTROL,
    PERMISSIONS.VIEW_GARBAGE,
    PERMISSIONS.CREATE_COMPLAINT, PERMISSIONS.VIEW_COMPLAINTS, PERMISSIONS.MANAGE_COMPLAINTS,
    PERMISSIONS.VIEW_SCORECARDS,
    PERMISSIONS.VIEW_EXECUTION
  ],

  RAILWAY_ADMIN: [
    PERMISSIONS.VIEW_USERS, PERMISSIONS.VIEW_USER_DETAILS, PERMISSIONS.VIEW_ENTITIES,
    PERMISSIONS.VIEW_CONTRACTS, PERMISSIONS.VIEW_TRAINS, PERMISSIONS.VIEW_RUN_INSTANCES,
    PERMISSIONS.VIEW_FORMS, PERMISSIONS.VIEW_REPORTS, PERMISSIONS.SUBMIT_COACH_FORM,
    PERMISSIONS.APPROVE_FORM_MANPOWER, PERMISSIONS.SCORE_FORM, PERMISSIONS.REJECT_FORM,
    PERMISSIONS.VIEW_PLATFORMS, PERMISSIONS.VIEW_AREAS,
    PERMISSIONS.VIEW_FREQUENCIES, PERMISSIONS.GENERATE_TASKS,
    PERMISSIONS.VIEW_SHIFTS, PERMISSIONS.ASSIGN_SHIFT,
    PERMISSIONS.VIEW_DEPLOYMENTS,
    PERMISSIONS.VIEW_GEOFENCES,
    PERMISSIONS.VIEW_INSPECTIONS, PERMISSIONS.APPROVE_INSPECTION, PERMISSIONS.SCORE_INSPECTION,
    PERMISSIONS.VIEW_PETTY_ISSUES, PERMISSIONS.RESOLVE_PETTY_ISSUE,
    PERMISSIONS.VIEW_SEARCH,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.VIEW_MACHINES,
    PERMISSIONS.VIEW_MATERIALS,
    PERMISSIONS.VIEW_PEST_CONTROL,
    PERMISSIONS.VIEW_GARBAGE,
    PERMISSIONS.CREATE_COMPLAINT, PERMISSIONS.VIEW_COMPLAINTS, PERMISSIONS.MANAGE_COMPLAINTS,
    PERMISSIONS.VIEW_SCORECARDS,
    PERMISSIONS.VIEW_EXECUTION
  ],

  RAILWAY_SUPERVISOR: [
    PERMISSIONS.VIEW_USERS, PERMISSIONS.VIEW_USER_DETAILS, PERMISSIONS.VIEW_TRAINS,
    PERMISSIONS.VIEW_RUN_INSTANCES, PERMISSIONS.VIEW_FORMS, PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.APPROVE_FORM_MANPOWER, PERMISSIONS.SCORE_FORM, PERMISSIONS.REJECT_FORM,
    PERMISSIONS.VIEW_PLATFORMS, PERMISSIONS.VIEW_AREAS,
    PERMISSIONS.VIEW_FREQUENCIES,
    PERMISSIONS.VIEW_SHIFTS,
    PERMISSIONS.VIEW_DEPLOYMENTS,
    PERMISSIONS.VIEW_GEOFENCES,
    PERMISSIONS.VIEW_INSPECTIONS, PERMISSIONS.SCORE_INSPECTION,
    PERMISSIONS.VIEW_PETTY_ISSUES,
    PERMISSIONS.VIEW_SEARCH,
    PERMISSIONS.VIEW_ACTIVITIES,
    PERMISSIONS.VIEW_MACHINES,
    PERMISSIONS.VIEW_MATERIALS,
    PERMISSIONS.VIEW_PEST_CONTROL,
    PERMISSIONS.VIEW_GARBAGE,
    PERMISSIONS.CREATE_COMPLAINT, PERMISSIONS.VIEW_COMPLAINTS,
    PERMISSIONS.VIEW_SCORECARDS,
    PERMISSIONS.VIEW_EXECUTION
  ],

  CONTRACTOR_SUPERVISOR: [
    PERMISSIONS.VIEW_USERS, PERMISSIONS.VIEW_USER_DETAILS, PERMISSIONS.VIEW_TRAINS,
    PERMISSIONS.VIEW_RUN_INSTANCES, PERMISSIONS.VIEW_FORMS, PERMISSIONS.SUBMIT_COACH_FORM,
    PERMISSIONS.ACCEPT_RATING,
    PERMISSIONS.VIEW_PLATFORMS, PERMISSIONS.VIEW_AREAS,
    PERMISSIONS.VIEW_SHIFTS,
    PERMISSIONS.VIEW_DEPLOYMENTS,
    PERMISSIONS.VIEW_GEOFENCES,
    PERMISSIONS.VIEW_INSPECTIONS,
    PERMISSIONS.VIEW_PETTY_ISSUES,
    PERMISSIONS.VIEW_SEARCH
  ],

  CTS: [
    PERMISSIONS.VIEW_TRAINS, PERMISSIONS.VIEW_RUN_INSTANCES, PERMISSIONS.CREATE_EMERGENCY_TASK
  ],

  WORKER: [
    PERMISSIONS.VIEW_RUN_INSTANCES
  ],

  RAILWAY_WORKER: [
    PERMISSIONS.VIEW_RUN_INSTANCES
  ],

  JANITOR: [
    PERMISSIONS.VIEW_RUN_INSTANCES
  ],

  ATTENDANT: [
    PERMISSIONS.VIEW_RUN_INSTANCES
  ]
});
