/*
 * Required Firestore composite indexes:
 *  1. `station_daily_activities` – `stationId` ASC, `date` ASC, `shift` ASC
 *  2. `station_daily_activities` – `stationId` ASC, `date` ASC, `status` ASC
 *  3. `station_daily_activities` – `assignedWorkers` (array), `date` ASC, `stationId` ASC
 *  4. `stationSchedules` – `stationId` ASC
 */

import { db, admin } from '../database/index.js';
import { NotFoundError, ValidationError } from '../errors/index.js';
import { paginate } from '../utils/paginate.js';
import logger from '../logger/index.js';

const VALID_STATUSES = ['PENDING', 'IN_PROGRESS', 'COMPLETED', 'PARTIALLY_COMPLETED', 'REJECTED', 'RESUBMITTED', 'APPROVED'];

class DailyActivityService {
  async createRecord(user, data) {
    const { stationId, areaId, activityId, date, shift, scheduledFrequency } = data;
    if (!stationId || !areaId || !activityId || !date || !shift) throw new ValidationError('stationId, areaId, activityId, date, and shift are required');

    const [stationDoc, areaDoc, activityDoc] = await Promise.all([
      db.collection('stations').doc(stationId).get(),
      db.collection('stationAreas').doc(areaId).get(),
      db.collection('activities').doc(activityId).get(),
    ]);
    if (!stationDoc.exists) throw new NotFoundError('Station not found');

    const now = new Date().toISOString();
    const ref = db.collection('station_daily_activities').doc();
    const record = {
      uid: ref.id, stationId, stationName: stationDoc.data().stationName || '',
      areaId, areaName: areaDoc.exists ? (areaDoc.data().name || '') : data.areaName || '',
      activityId, activityName: activityDoc.exists ? (activityDoc.data().name || '') : data.activityName || '',
      date, shift: shift.toLowerCase(), scheduledFrequency: scheduledFrequency || 'once_per_day',
      status: 'PENDING',
      assignedWorkers: data.assignedWorkers || [],
      timeStarted: null, timeCompleted: null,
      beforePhotoUrl: data.beforePhotoUrl || '', afterPhotoUrl: data.afterPhotoUrl || '',
      remarks: data.remarks || '',
      submittedBy: user.uid, submittedByName: user.fullName || user.name || '',
      submittedAt: null, verifiedBy: null, verifiedByName: null, verifiedAt: null,
      rejectionReason: null, resubmissionRemarks: null,
      auditLog: [{ action: 'CREATED', by: user.uid, byName: user.fullName || '', at: now }],
      autoGenerated: data.autoGenerated || false,
      createdAt: now, updatedAt: now,
    };
    await ref.set(record);
    return { message: 'Activity record created', uid: ref.id, record };
  }

  async autoGenerateFromSchedule(stationId, date, shift) {
    if (!stationId || !date || !shift) throw new ValidationError('stationId, date, and shift are required');
    const [schedulesSnap, areasSnap] = await Promise.all([
      db.collection('stationSchedules').where('stationId', '==', stationId).get(),
      db.collection('stationAreas').where('stationId', '==', stationId).get(),
    ]);
    if (schedulesSnap.empty) return { generated: 0, message: 'No schedules found for this station' };

    const dayOfWeek = new Date(date).toLocaleDateString('en', { weekday: 'long' }).toLowerCase();
    const areaMap = {}; areasSnap.forEach(d => { areaMap[d.id] = d.data().name; });
    const stationDoc = await db.collection('stations').doc(stationId).get();
    const stationName = stationDoc.exists ? stationDoc.data().stationName : '';

    let generated = 0;
    const adminUser = { uid: 'system', fullName: 'System Auto-Gen', name: 'System' };

    for (const sDoc of schedulesSnap.docs) {
      const s = sDoc.data();
      if (s.shift !== shift && s.shift !== 'all') continue;
      if (s.daysOfWeek && !s.daysOfWeek.includes(dayOfWeek) && !s.daysOfWeek.includes('all')) continue;

      const existingSnap = await db.collection('station_daily_activities')
        .where('stationId', '==', stationId).where('date', '==', date)
        .where('shift', '==', shift).where('areaId', '==', s.areaId)
        .where('activityId', '==', s.activityId).limit(1).get();
      if (!existingSnap.empty) continue;

      await this.createRecord(adminUser, {
        stationId, areaId: s.areaId, areaName: s.areaName || areaMap[s.areaId] || '',
        activityId: s.activityId, activityName: s.activityName || '',
        date, shift, scheduledFrequency: s.frequency || 'once_per_day',
        assignedWorkers: s.assignedWorkers || [],
        autoGenerated: true, remarks: 'Auto-generated',
      });
      generated++;
    }
    return { generated, message: `${generated} activities auto-generated` };
  }

  async startActivity(uid, user) {
    const ref = db.collection('station_daily_activities').doc(uid);
    const doc = await ref.get();
    if (!doc.exists) throw new NotFoundError('Activity record not found');
    if (doc.data().status !== 'PENDING') throw new ValidationError('Only PENDING activities can be started');
    await ref.update({ status: 'IN_PROGRESS', timeStarted: new Date().toISOString(), updatedAt: new Date().toISOString() });
    return { message: 'Activity started', uid };
  }

  async completeActivity(uid, user, body) {
    const ref = db.collection('station_daily_activities').doc(uid);
    const doc = await ref.get();
    if (!doc.exists) throw new NotFoundError('Activity record not found');
    if (doc.data().status !== 'IN_PROGRESS') throw new ValidationError('Only IN_PROGRESS activities can be completed');
    const updates = { status: 'COMPLETED', timeCompleted: new Date().toISOString(), updatedAt: new Date().toISOString(), submittedAt: new Date().toISOString() };
    if (body.afterPhotoUrl) updates.afterPhotoUrl = body.afterPhotoUrl;
    if (body.beforePhotoUrl) updates.beforePhotoUrl = body.beforePhotoUrl;
    if (body.remarks) updates.remarks = body.remarks;
    await ref.update(updates);
    return { message: 'Activity completed', uid };
  }

  async updateStatus(uid, status, user, extra = {}) {
    if (!VALID_STATUSES.includes(status)) throw new ValidationError(`status must be one of: ${VALID_STATUSES.join(', ')}`);
    const ref = db.collection('station_daily_activities').doc(uid);
    const doc = await ref.get();
    if (!doc.exists) throw new NotFoundError('Activity record not found');
    const current = doc.data();
    const now = new Date().toISOString();
    const transitions = { PENDING: ['IN_PROGRESS', 'COMPLETED', 'PARTIALLY_COMPLETED'], IN_PROGRESS: ['COMPLETED', 'PARTIALLY_COMPLETED'], COMPLETED: ['APPROVED', 'REJECTED'], PARTIALLY_COMPLETED: ['APPROVED', 'REJECTED'], REJECTED: ['RESUBMITTED'], RESUBMITTED: ['APPROVED', 'REJECTED'], APPROVED: [] };
    if (!transitions[current.status]?.includes(status)) throw new ValidationError(`Cannot transition from '${current.status}' to '${status}'`);

    const updates = { status, updatedAt: now, auditLog: admin.firestore.FieldValue.arrayUnion({ action: status, by: user.uid, byName: user.fullName || '', at: now, details: extra.remarks || extra.rejectionReason || '' }) };
    if (['COMPLETED', 'PARTIALLY_COMPLETED'].includes(status)) { updates.submittedAt = now; if (extra.afterPhotoUrl) updates.afterPhotoUrl = extra.afterPhotoUrl; if (extra.beforePhotoUrl) updates.beforePhotoUrl = extra.beforePhotoUrl; if (extra.remarks) updates.remarks = extra.remarks; }
    if (['APPROVED', 'REJECTED'].includes(status)) { updates.verifiedBy = user.uid; updates.verifiedByName = user.fullName || ''; updates.verifiedAt = now; }
    if (status === 'REJECTED' && extra.rejectionReason) updates.rejectionReason = extra.rejectionReason;
    if (status === 'RESUBMITTED' && extra.resubmissionRemarks) { updates.resubmissionRemarks = extra.resubmissionRemarks; updates.rejectionReason = null; }
    await ref.update(updates);
    return { message: `Status updated to ${status}`, uid, status };
  }

  async listActivities(query = {}) {
    const { stationId, areaId, activityId, date, shift, status, assignedWorker, limit = 100, cursor } = query;
    let q = db.collection('station_daily_activities');
    if (stationId) q = q.where('stationId', '==', stationId);
    if (areaId) q = q.where('areaId', '==', areaId);
    if (activityId) q = q.where('activityId', '==', activityId);
    if (date) q = q.where('date', '==', date);
    if (shift && shift !== 'all') q = q.where('shift', '==', shift.toLowerCase());
    if (status) q = q.where('status', '==', status);
    const result = await paginate(q, { limit, cursor, orderBy: 'createdAt', orderDir: 'desc' });
    return { count: result.items.length, activities: result.items, pagination: result.pagination };
  }

  async getById(uid) {
    const doc = await db.collection('station_daily_activities').doc(uid).get();
    if (!doc.exists) throw new NotFoundError('Activity record not found');
    return { id: doc.id, ...doc.data() };
  }

  async getMissedActivities(stationId, date, shift) {
    if (!stationId || !date) throw new ValidationError('stationId and date are required');
    const [schedulesSnap, doneSnap] = await Promise.all([
      db.collection('stationSchedules').where('stationId', '==', stationId).get(),
      db.collection('station_daily_activities').where('stationId', '==', stationId).where('date', '==', date).where('status', 'in', ['COMPLETED', 'APPROVED', 'PARTIALLY_COMPLETED']).get()
    ]);
    const doneKeys = new Set();
    doneSnap.forEach(doc => { const d = doc.data(); doneKeys.add(`${d.areaId}_${d.activityId}_${d.shift}`); });
    const missed = [];
    schedulesSnap.forEach(doc => {
      const s = doc.data();
      if (shift && shift !== 'all' && s.shift !== shift) return;
      const key = `${s.areaId}_${s.activityId || ''}_${s.shift}`;
      if (!doneKeys.has(key)) missed.push({ stationId, date, areaId: s.areaId, areaName: s.areaName || '', activityId: s.activityId || '', activityName: s.activityName || '', shift: s.shift, frequency: s.frequency, scheduledId: doc.id, missedAt: new Date().toISOString() });
    });
    return { stationId, date, shift: shift || 'all', missedCount: missed.length, missed };
  }

  async getPendingActivities(stationId, date, shift, workerId) {
    if (!stationId || !date) throw new ValidationError('stationId and date are required');
    let q = db.collection('station_daily_activities').where('stationId', '==', stationId).where('date', '==', date).where('status', 'in', ['PENDING', 'REJECTED', 'IN_PROGRESS']);
    if (shift && shift !== 'all') q = q.where('shift', '==', shift.toLowerCase());
    if (workerId) q = q.where('submittedBy', '==', workerId);
    const snapshot = await q.limit(200).get();
    const activities = []; snapshot.forEach(doc => activities.push({ id: doc.id, ...doc.data() }));
    return { stationId, date, count: activities.length, activities };
  }

  async getWorkerActivities(stationId, date, shift, workerId) {
    if (!stationId || !workerId) throw new ValidationError('stationId and workerId are required');
    const snapshot = await db.collection('station_daily_activities').where('stationId', '==', stationId).where('date', '==', date || new Date().toISOString().split('T')[0]).where('assignedWorkers', 'array-contains', workerId).limit(100).get();
    const activities = []; snapshot.forEach(doc => activities.push({ id: doc.id, ...doc.data() }));
    return { workerId, count: activities.length, activities };
  }

  async getShiftSummary(stationId, date, shift) {
    if (!stationId || !date || !shift) throw new ValidationError('stationId, date, shift are required');
    const snapshot = await db.collection('station_daily_activities').where('stationId', '==', stationId).where('date', '==', date).where('shift', '==', shift.toLowerCase()).get();
    const summary = { total: 0, PENDING: 0, IN_PROGRESS: 0, COMPLETED: 0, PARTIALLY_COMPLETED: 0, APPROVED: 0, REJECTED: 0, RESUBMITTED: 0 };
    snapshot.forEach(doc => { summary.total++; const s = doc.data().status; if (summary[s] !== undefined) summary[s]++; });
    const completionRate = summary.total > 0 ? Math.round(((summary.COMPLETED + summary.APPROVED + summary.PARTIALLY_COMPLETED) / summary.total) * 100) : 0;
    return { stationId, date, shift, summary, completionRate };
  }

  async bulkVerify(uids, status, user, remarks) {
    if (!['APPROVED', 'REJECTED'].includes(status)) throw new ValidationError('status must be APPROVED or REJECTED');
    const now = new Date().toISOString();
    const batch = db.batch(); let count = 0;
    for (const uid of uids) {
      const ref = db.collection('station_daily_activities').doc(uid);
      batch.update(ref, { status, verifiedBy: user.uid, verifiedByName: user.fullName || '', verifiedAt: now, updatedAt: now, rejectionReason: status === 'REJECTED' ? (remarks || 'No reason given') : null, auditLog: admin.firestore.FieldValue.arrayUnion({ action: status, by: user.uid, byName: user.fullName || '', at: now, details: remarks || '' }) });
      count++;
    }
    await batch.commit();
    return { message: `${count} activities ${status}`, count, status };
  }

  async deleteRecord(uid) {
    const ref = db.collection('station_daily_activities').doc(uid);
    const doc = await ref.get();
    if (!doc.exists) throw new NotFoundError('Activity record not found');
    await ref.update({ status: 'DELETED', deletedAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
    return { message: 'Activity record deleted' };
  }
}

export const dailyActivityService = new DailyActivityService();
