import { db } from '../database/index.js';
import { NotFoundError, ValidationError } from '../errors/index.js';
import { paginate } from '../utils/paginate.js';

const VALID_STATUSES = ['DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED'];

class ScorecardService {
  async createDailyScorecard(userData, body) {
    const { stationId, date, areaWiseScores, overallStationScore, inspectorName, platformId } = body;
    if (!stationId || !date || overallStationScore === undefined) throw new ValidationError('stationId, date, and overallStationScore are required');

    const existing = await db.collection('daily_scorecards')
      .where('stationId', '==', stationId)
      .where('date', '==', date)
      .where('status', 'in', ['DRAFT', 'SUBMITTED', 'APPROVED'])
      .limit(1).get();
    if (!existing.empty) throw new ValidationError('A scorecard already exists for this station on this date');

    const stationDoc = await db.collection('stations').doc(stationId).get();
    if (!stationDoc.exists) throw new NotFoundError('Station not found');

    const ref = db.collection('daily_scorecards').doc();
    const data = {
      uid: ref.id, stationId, stationName: stationDoc.data().stationName || '',
      platformId: platformId || null, date,
      areaWiseScores: areaWiseScores || {},
      areaWisePlatformScores: body.areaWisePlatformScores || {},
      overallStationScore,
      grade: this.calculateGrade(overallStationScore),
      inspectorName: inspectorName || userData.fullName || '',
      inspectorDesignation: body.inspectorDesignation || '',
      remarks: body.remarks || '',
      status: 'DRAFT',
      certified: false, certifiedBy: null, certifiedAt: null,
      forwardedToCommercial: false, forwardedToCommercialAt: null,
      submittedBy: null, submittedAt: null,
      approvedBy: null, approvedAt: null,
      rejectionReason: null,
      autoGenerated: body.autoGenerated || false,
      sourceInspectionIds: body.sourceInspectionIds || [],
      createdBy: userData.uid, createdByName: userData.fullName || userData.name || '',
      createdAt: new Date().toISOString(), updatedAt: new Date().toISOString()
    };
    await ref.set(data);
    return { message: 'Daily scorecard created', uid: ref.id, scorecard: data };
  }

  async submitScorecard(uid, userData) {
    const ref = db.collection('daily_scorecards').doc(uid);
    const doc = await ref.get();
    if (!doc.exists) throw new NotFoundError('Scorecard not found');
    if (doc.data().status !== 'DRAFT') throw new ValidationError('Only DRAFT scorecards can be submitted');
    await ref.update({ status: 'SUBMITTED', submittedBy: userData.uid, submittedAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
    return { message: 'Scorecard submitted for approval' };
  }

  async approveScorecard(uid, userData, body) {
    const ref = db.collection('daily_scorecards').doc(uid);
    const doc = await ref.get();
    if (!doc.exists) throw new NotFoundError('Scorecard not found');
    if (doc.data().status !== 'SUBMITTED') throw new ValidationError('Only SUBMITTED scorecards can be approved');
    await ref.update({
      status: 'APPROVED', certified: body.certified !== false, certifiedBy: userData.uid,
      certifiedAt: new Date().toISOString(), approvedBy: userData.uid,
      approvedAt: new Date().toISOString(), updatedAt: new Date().toISOString(),
      forwardedToCommercial: body.forwardToCommercial || false,
      forwardedToCommercialAt: body.forwardToCommercial ? new Date().toISOString() : null,
    });
    return { message: 'Scorecard approved' };
  }

  async rejectScorecard(uid, userData, body) {
    const ref = db.collection('daily_scorecards').doc(uid);
    const doc = await ref.get();
    if (!doc.exists) throw new NotFoundError('Scorecard not found');
    if (doc.data().status !== 'SUBMITTED') throw new ValidationError('Only SUBMITTED scorecards can be rejected');
    await ref.update({ status: 'REJECTED', rejectionReason: body.reason || '', rejectedBy: userData.uid, rejectedAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
    return { message: 'Scorecard rejected' };
  }

  async autoGenerateFromInspections(stationId, date) {
    const snap = await db.collection('inspections')
      .where('stationId', '==', stationId)
      .where('scheduledDate', '==', date)
      .where('status', 'in', ['COMPLETED', 'APPROVED'])
      .get();

    if (snap.empty) return { generated: false, message: 'No completed inspections found for this date' };

    let totalScore = 0; let count = 0; const areaScores = {}; const inspectionIds = [];
    snap.forEach(doc => {
      const d = doc.data();
      inspectionIds.push(doc.id);
      if (d.overallScore) { totalScore += d.overallScore; count++; }
      const ratings = d.ratings || {};
      for (const [area, score] of Object.entries(ratings)) {
        areaScores[area] = (areaScores[area] || 0) + score;
      }
    });

    const avgScore = count > 0 ? Math.round(totalScore / count) : 70;
    const averagedAreas = {};
    for (const [area, total] of Object.entries(areaScores)) {
      averagedAreas[area] = Math.round(total / count);
    }

    const adminUser = { uid: 'system', fullName: 'System Auto-Generate', name: 'System' };
    return this.createDailyScorecard(adminUser, {
      stationId, date, areaWiseScores: averagedAreas,
      overallStationScore: avgScore,
      inspectorName: 'Auto-generated from Inspections',
      autoGenerated: true, sourceInspectionIds: inspectionIds
    });
  }

  async getDailyScorecards(query = {}) {
    const { stationId, date, startDate, endDate, status, platformId, limit = 50, cursor } = query;
    let q = db.collection('daily_scorecards');
    if (stationId) q = q.where('stationId', '==', stationId);
    if (date) q = q.where('date', '==', date);
    if (status) q = q.where('status', '==', status);
    if (platformId) q = q.where('platformId', '==', platformId);
    if (startDate) q = q.where('date', '>=', startDate);
    if (endDate) q = q.where('date', '<=', endDate);
    const result = await paginate(q, { limit, cursor, orderBy: 'date', orderDir: 'desc' });
    return { count: result.items.length, scorecards: result.items, pagination: result.pagination };
  }

  async getMonthlyScorecard(stationId, month, year) {
    if (!stationId || !month || !year) throw new ValidationError('stationId, month, and year are required');
    const monthPad = String(month).padStart(2, '0');
    const startDate = `${year}-${monthPad}-01`;
    const endDate = `${year}-${monthPad}-31`;

    const snapshot = await db.collection('daily_scorecards')
      .where('stationId', '==', stationId)
      .where('date', '>=', startDate)
      .where('date', '<=', endDate).get();

    const scorecards = [];
    snapshot.forEach(doc => scorecards.push(doc.data()));
    if (scorecards.length === 0) return { stationId, month, year, averageScore: 0, totalDays: 0, scorecards: [] };

    const total = scorecards.reduce((s, c) => s + (c.overallStationScore || 0), 0);
    const avg = Math.round(total / scorecards.length);
    const best = Math.max(...scorecards.map(c => c.overallStationScore || 0));
    const worst = Math.min(...scorecards.map(c => c.overallStationScore || 0));
    const grades = {};
    scorecards.forEach(c => { const g = c.grade || 'N/A'; grades[g] = (grades[g] || 0) + 1; });

    const trend = scorecards.sort((a, b) => a.date.localeCompare(b.date)).map(c => ({
      date: c.date, score: c.overallStationScore, grade: c.grade
    }));

    return {
      stationId, month, year, totalDays: scorecards.length,
      averageScore: avg, bestScore: best, worstScore: worst,
      gradeDistribution: grades, certified: scorecards.every(c => c.certified),
      scoresByDate: trend, scorecards
    };
  }

  async getScorecardById(uid) {
    const doc = await db.collection('daily_scorecards').doc(uid).get();
    if (!doc.exists) throw new NotFoundError('Scorecard not found');
    return { id: doc.id, ...doc.data() };
  }

  async updateScorecard(uid, body) {
    const ref = db.collection('daily_scorecards').doc(uid);
    const doc = await ref.get();
    if (!doc.exists) throw new NotFoundError('Scorecard not found');
    if (doc.data().status !== 'DRAFT') throw new ValidationError('Only DRAFT scorecards can be edited');
    const allowed = ['areaWiseScores', 'areaWisePlatformScores', 'overallStationScore', 'inspectorName', 'inspectorDesignation', 'remarks', 'platformId'];
    const updates = {};
    for (const key of allowed) {
      if (body[key] !== undefined) updates[key] = body[key];
    }
    if (body.overallStationScore !== undefined) {
      updates.grade = this.calculateGrade(body.overallStationScore);
    }
    updates.updatedAt = new Date().toISOString();
    await ref.update(updates);
    return { message: 'Scorecard updated', uid };
  }

  async deleteScorecard(uid) {
    const ref = db.collection('daily_scorecards').doc(uid);
    const doc = await ref.get();
    if (!doc.exists) throw new NotFoundError('Scorecard not found');
    if (!['DRAFT', 'REJECTED'].includes(doc.data().status)) throw new ValidationError('Only DRAFT or REJECTED scorecards can be deleted');
    await ref.update({ status: 'DELETED', deletedAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
    return { message: 'Scorecard deleted' };
  }

  calculateGrade(score) {
    if (score >= 90) return 'A';
    if (score >= 80) return 'B';
    if (score >= 70) return 'C';
    if (score >= 60) return 'D';
    return 'E';
  }
}

export const scorecardService = new ScorecardService();
