// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: 'AIzaSyDofeMfQEhZuuYlRvWkiuLwceTWe7zOUYE',
        appId: '1:271410388492:web:ee67606101eb88aa6f9829', // reused from android with web prefix
        messagingSenderId: '271410388492',
        projectId: 'swachh-railways',
        storageBucket: 'swachh-railways.firebasestorage.app',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDofeMfQEhZuuYlRvWkiuLwceTWe7zOUYE',
    appId: '1:271410388492:android:ee67606101eb88aa6f9829',
    messagingSenderId: '271410388492',
    projectId: 'swachh-railways',
    storageBucket: 'swachh-railways.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFa-0vjYjd1OGpYHTbewS1sqCW-k_kDsA',
    appId: '1:271410388492:ios:e1f8094b4b9cf5046f9829',
    messagingSenderId: '271410388492',
    projectId: 'swachh-railways',
    storageBucket: 'swachh-railways.firebasestorage.app',
    iosBundleId: 'com.swachhrailway.app',
  );
}
